# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Test' do
pod "AFNetworking", "~>2"
pod "SDWebImage", "~>3"
pod 'FXBlurView', '~> 1.6'
end

target 'TestTests' do

end

